blank_issues_enabled: true
contact_links:
  - name: BlockSync Core Discussions
    url: https://github.com/BlockSyncHQ/blocksync/discussions
    about: Please ask and answer questions here.
  - name: BlockSync support
    email: n3v1010@gmail.com
    about: support email