name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, thanks for reporting this issue - @N3v1 and @iiiiftekhar will look into your issue. Our team is normally responding between 9am to 9pm UTC."
        pr-message: "Hi there, thanks for creating this pull request - @N3v1 will review your pull request. Our team is normally responding between 9am to 9pm UTC."
