name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, Thank you for reporting this issue - @N3v1  will look into your issue. To make communication even better join our Discord Community [here]() `(not available yet)`."
        pr-message: "Hi there, Thank you for creating this PR - @N3v1  will look into your PR. To make communication even better join our Discord Community [here]() `(not available yet)`."
